export {default as Footer} from './Footer'
export {default as Header} from './Header'
export {default as Categories} from './Categories'
export {default as PizzaBlock} from './PizzaBlock/PizzaBlock'
export {default as Sort} from './Sort'
export {default as Search} from './UI/Search/Search'